### PR TITLE
fix(builder): Defer graph validation to backend

### LINKED ISSUE #10553: Fix graph validation failure with passed-in credentials
`useAgentGraph:saveAndRun(..)` fails with a validation error if a graph has blocks with unset credential inputs, even if those credentials are passed in with the `credentialsInputs` argument. This is because a validation step is done in the *frontend* which doesn't take the passed-in credentials into account.

Ideally we do validation in one place: the backend. We can let the backend generate errors that the frontend can parse and show in all the right places.

### PR DESCRIPTION
**Pull request by Pwuts**
- Resolves #10553

### Changes 🏗️

- Remove frontend graph validation in `useAgentGraph:saveAndRun(..)`
  - Remove now unused `ajv` dependency
- Implement graph validation error propagation (backend->frontend)
  - Add `GraphValidationError` type in frontend and backend
  - Add `GraphModel.validate_graph_get_errors(..)` method
  - Fix error handling & propagation in frontend API request logic

#### For code changes:
- [x] I have clearly listed my changes in the PR description
- [x] I have made a test plan
- [x] I have tested my changes according to the test plan:
  - [x] Saving & running a graph with missing required inputs gives a node-specific error
  - [x] Saving & running a graph with missing node credential inputs succeeds with passed-in credentials

### CODE REVIEW

**Comment by AutoGPT-Agent** [comment]
Thank you for this PR to improve graph validation by moving it to the backend! This change makes a lot of sense since the backend has access to more context than the frontend.

### What looks good:
- The code structure is solid, introducing a more robust validation approach with structured error responses
- You've properly implemented error handling and propagation between backend and frontend
- The PR description clearly states the changes and includes a reference to the issue

### Before this can be merged:

You need to complete the testing according to your test plan. Your checklist indicates you have:
- Not verified that "Saving & running a graph with missing required inputs gives a node-specific error"
- Not verified that "Saving & running a graph with missing node credential inputs succeeds with passed-in credentials"

Please complete your testing and update the checklist once you've confirmed the functionality works as expected. This will help ensure we don't introduce any regressions with this change.

Would you like any help with testing or have any questions about implementing these test cases?

**Comment by AutoGPT-Agent** [comment]
Thank you for this PR which moves graph validation from the frontend to the backend. This is a good architectural improvement that centralizes validation logic.

### Feedback

Your implementation looks solid - you've:

1. Added structured validation error handling in the backend
2. Created proper error propagation to the frontend
3. Removed the frontend validation logic and ajv dependency
4. Added helpful error reporting for node-specific validation issues

However, I notice that you haven't completed testing according to your test plan. Before this can be merged, please:

- Complete the test cases you outlined in your checklist:
  - Saving & running a graph with missing required inputs gives a node-specific error
  - Saving & running a graph with missing node credential inputs succeeds with passed-in credentials

Once you've verified these test cases, please check them off in the PR description.

Aside from that, the implementation looks good and follows a clean approach to error handling between the backend and frontend.

File: autogpt_platform/frontend/src/lib/autogpt-server-api/helpers.ts [hunk 1]
```diff
@@ -2,16 +2,33 @@ import { getServerSupabase } from "@/lib/supabase/server/getServerSupabase";
...
     this.status = status;
     this.response = response;
   }
+
+  /**
+   * Type guard to check if this error is a structured graph validation error
+   */
+  isGraphValidationError(): this is ApiError<GraphValidationErrorResponse> {
+    return (
+      this.response !== undefined &&
```
Comment (majdyz) [inline autogpt_platform/frontend/src/lib/autogpt-server-api/helpers.ts:23]: null check already includes undefined?

**Comment by AutoGPT-Agent** [comment]
Thank you for working on deferring graph validation to the backend! This is a significant improvement to the validation system, creating a more robust process where the backend can provide structured errors that the frontend can interpret and display.

The changes look good technically, with a clear approach to:
1. Add structured validation capability to the backend
2. Remove the redundant Ajv validation from the frontend
3. Implement proper error propagation from backend to frontend

However, before this PR can be merged, you need to complete your test plan. I notice that you've outlined a specific test plan but haven't checked off the test items:

- [ ] Saving & running a graph with missing required inputs gives a node-specific error
- [ ] Saving & running a graph with missing node credential inputs succeeds with passed-in credentials

Please complete the testing according to your plan and check off these items. This verification is important to ensure the new validation system works correctly in all the specified scenarios.

Once you've completed the testing and updated the checklist, this PR should be ready for another review.

**Comment by AutoGPT-Agent** [comment]
Thank you for your PR implementing the deferral of graph validation to the backend! This is a good architectural improvement that will centralize validation logic and allow for more comprehensive error checking.

### Feedback

**Great work on:**
- Creating a structured validation error system that can communicate specific node errors back to the frontend
- Properly removing the now-redundant frontend validation using Ajv
- Adding helpful documentation comments throughout the code
- Implementing proper error type checking in the frontend

**Before merging:**
- The test plan in your checklist is not marked as completed. Could you please complete the testing according to your plan and mark those items as checked?
  - Specifically, testing that saving & running a graph with missing required inputs gives node-specific errors
  - And testing that saving & running a graph with missing node credential inputs succeeds with passed-in credentials

This validation is important since this change shifts responsibility from frontend to backend, and we need to ensure the new error propagation works correctly.

Once you've completed the testing and checked off those items in the checklist, this PR should be ready for another review.

**Comment by AutoGPT-Agent** [comment]
Thank you for your PR to defer graph validation to the backend. The implementation looks solid and well-structured, particularly the new error handling approach that provides better feedback to users.

A few observations:

1. **Test Plan**: It appears you've created a good test plan but haven't completed testing according to it yet. Please ensure you test both scenarios:
   - Saving & running a graph with missing required inputs gives node-specific errors
   - Saving & running a graph with missing node credential inputs succeeds with passed-in credentials

2. **Implementation details**:
   - Good job restructuring the validation code to return structured errors instead of just raising exceptions
   - The frontend changes to handle structured validation errors from the backend are well-implemented
   - Removing the frontend AJV dependency is a good cleanup

3. **Documentation**:
   - The added docstrings in the backend code are helpful for understanding the new validation flow

Once you've completed testing according to your test plan and checked off those items in the PR description, this should be ready for another review.

**Comment by AutoGPT-Agent** [comment]
Thanks for working on this improvement to move graph validation to the backend! This is a well-structured PR that makes the validation more robust.

A few comments:

1. **Checklist Completion**: Please complete your test plan by checking off the test items you've already defined:
   - [ ] Saving & running a graph with missing required inputs gives a node-specific error
   - [ ] Saving & running a graph with missing node credential inputs succeeds with passed-in credentials

2. **Good Work on Structured Validation**: The new approach to return structured validation errors from the backend to the frontend is well-implemented. This provides better user feedback and a more maintainable architecture.

3. **Nice Job Removing Frontend Validation**: Removing the client-side validation in favor of the backend validation is a good architectural choice, especially since the backend has access to more context (like credentials).

4. **Error Propagation**: The error propagation from backend to frontend is well-implemented with a clear type system.

Once you've completed and checked off the test plan items, this PR should be ready to merge. Let us know if you encounter any issues during testing!

**Comment by AutoGPT-Agent** [comment]
Thank you for the PR to defer graph validation to the backend. This is a good architectural improvement that will provide more consistent validation between frontend and backend.

### Feedback

The code changes look well-structured and comprehensive. You've successfully:

1. Removed the Ajv dependency from the frontend
2. Created structured validation error responses from the backend
3. Implemented proper error handling and display in the frontend
4. Added detailed documentation for the new validation methods

However, there are a couple of things that need to be addressed before this can be merged:

#### Testing

According to your checklist, you haven't yet tested the changes according to your test plan. Please complete the testing for:

- Saving & running a graph with missing required inputs gives a node-specific error
- Saving & running a graph with missing node credential inputs succeeds with passed-in credentials

Once you've verified these scenarios work correctly, please update the PR by checking off the test items.

#### Minor Suggestions

- Consider adding a few unit tests for the new `validate_graph_get_errors` method to ensure it catches different types of validation errors correctly
- The error message display in the frontend could potentially be improved with more specific guidance for users on how to fix the validation errors

Overall, this is a good architectural improvement that will make the validation more robust and consistent. Please complete the testing and update the PR accordingly.

**Comment by AutoGPT-Agent** [comment]
Thank you for this PR to defer graph validation to the backend! The implementation looks solid and will provide better validation error reporting to users.

I noticed your test plan items are unchecked - could you please verify that you've tested:
- Saving & running a graph with missing required inputs gives a node-specific error
- Saving & running a graph with missing node credential inputs succeeds with passed-in credentials

Once you've completed testing, please check off those items in the PR description.

The implementation approach looks good:
- You've added proper structured error reporting from backend to frontend
- The `GraphValidationError` class enables propagating node-specific errors
- Removal of client-side validation in favor of backend validation is a good architectural decision
- The credential validation is now properly integrated into the overall validation flow

Nice work on removing the unused `ajv` dependency as well!

**Comment by AutoGPT-Agent** [comment]
Thank you for implementing the backend graph validation! This is a good architectural improvement that will ensure consistent validation logic across the system.

### Review Feedback

#### Test Plan Completion
I noticed your test plan is only partially complete - you've verified that saving and running a graph with missing node credential inputs succeeds with passed-in credentials, but haven't yet confirmed that saving and running a graph with missing required inputs gives a node-specific error. Can you complete this testing before we merge?

#### Code Quality
The implementation looks solid overall! I like the structured error approach with the `GraphValidationError` class and how you're propagating errors to the frontend in a way that allows for specific node-level highlighting.

The removal of client-side validation in `useAgentGraph.tsx` and adding proper error handling for backend validation responses is a good approach. This centralizes the validation logic on the backend where it has access to all necessary data (like credentials).

#### Minor Suggestions
- Consider adding JSDoc comments to the new `isGraphValidationError()` type guard in the frontend for better developer documentation
- You might want to add a unit test specifically for the new validation functionality to ensure it remains stable

Please complete the test plan by verifying the missing required inputs scenario, and then this should be ready to merge.

**Comment by AutoGPT-Agent** [comment]
Thank you for your PR to defer graph validation to the backend!

### Feedback

Your changes look solid overall, with a good approach to moving validation to the backend and implementing structured error reporting. However, I noticed your test plan isn't fully completed:

- You've checked off testing for "Saving & running a graph with missing node credential inputs succeeds with passed-in credentials"
- But you haven't completed testing for "Saving & running a graph with missing required inputs gives a node-specific error"

Before we can merge this PR, could you please complete the remaining test plan item? This will ensure that both the happy path and error paths are verified to be working correctly.

The implementation itself looks good:
- Removing frontend validation in favor of backend validation makes sense
- The structured error handling between backend and frontend is well designed
- You've maintained backward compatibility with existing code while adding new functionality

Please complete the test plan, and we should be good to merge this PR.

**Comment by AutoGPT-Agent** [comment]
Thanks for this PR to defer graph validation to the backend! The implementation looks solid, with good error handling and propagation between the backend and frontend.

I see you've refactored the validation logic to provide structured errors that can be displayed directly on the nodes in the UI. The removal of the frontend validation with `ajv` in favor of backend validation makes sense, especially since the backend has access to credential information that the frontend doesn't.

However, I noticed your test plan is only partially completed. Before merging, could you please:

- Complete testing of the scenario: "Saving & running a graph with missing required inputs gives a node-specific error"

This is important to verify that the error propagation is working as expected in the most common validation failure case.

Also, a few minor points:

1. The structured error handling in `ApiError.isGraphValidationError()` is a nice touch for type safety.
2. Your implementation of node-specific errors will make the UX much better for users.

Once you've completed the remaining test case, this PR should be ready to merge.

**Review by majdyz — APPROVED** [review]
