### PR TITLE
fix(frontend): show all agent outputs instead of only the last one

### LINKED ISSUE #9175: Only The Last Output Shows in "Agent Outputs" Panel
The "Agent Outputs" panel currently only shows the final output for Agents that output several times during a single run. <br><br>This panel should instead show all the outputs of that run.

### PR DESCRIPTION
**Pull request by majiayu000**
Fixes #9175

### Changes 🏗️

The Agent Outputs panel only displayed the last execution result per output node, discarding all prior outputs during a run.

**Root cause:** In `AgentOutputs.tsx`, the `outputs` useMemo extracted only the last element from `nodeExecutionResults`:
```tsx
const latestResult = executionResults[executionResults.length - 1];
```

**Fix:** Changed `.map()` to `.flatMap()` over output nodes, iterating through all `executionResults` for each node. Each execution result now gets its own renderer lookup and metadata entry, so the panel shows every output produced during the run.

#### For code changes:
- [x] I have clearly listed my changes in the PR description
- [x] I have made a test plan
- [x] I have tested my changes according to the test plan:
  - [x] Verified TypeScript compiles without errors
  - [x] Confirmed the flatMap logic correctly iterates all execution results
  - [x] Verified existing filter for null renderers is preserved
  - [x] Run an agent with multiple outputs and confirm all show in the panel

### CODE REVIEW

**Comment by majdyz** [comment]
## Review: PR #12504 (show all agent outputs)

Good UX fix. Changes from showing only the last output to showing all outputs from execution results.

### Observations

1. **`flatMap` replaces `map`** -- correct approach to flatten multiple results per node into a single array.

2. **Filter on `result.output_data?.output !== undefined`** -- properly excludes results without output data.

3. **Potential concern: output ordering** -- `executionResults` are iterated in array order. If results are not sorted by execution time, outputs may appear in unexpected order. Verify that the array is already sorted.

4. **Potential concern: large output volume** -- if an agent runs many iterations (e.g., a loop that produces 100+ outputs), this will render ALL of them. Consider whether pagination or a "show more" pattern would be needed for agents with high output volume.

5. **All outputs share the same `name` from `node.data.hardcodedValues?.name`** -- so if there are multiple outputs, they'll all be labeled identically (e.g., "Output", "Output", "Output"). The user won't know which execution produced which output. Consider adding an index or timestamp.

**Verdict: LGTM** -- items 4/5 are nice-to-haves for follow-up.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx [hunk 1]
```diff
@@ -37,25 +37,27 @@ export const AgentOutputs = ({ flowID }: { flowID: string | null }) => {
...
-            : undefined;
-        const outputData = latestResult?.output_data?.output;
+        if (executionResults.length === 0) return [];
 
-        const renderer = globalRegistry.getRenderer(outputData);
+        return executionResults
+          .filter((result) => result.output_data?.output !== undefined)
+          .map((result) => {
+            const outputData = result.output_data?.output;
+            const renderer = globalRegistry.getRenderer(outputData);
```
Comment (majdyz) [inline autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx:61]: 🤖 🟠 **Should Fix**: Every execution result from the same output node gets the identical `metadata.name` and `metadata.description`. When an output node produces 5 results, the panel will show the heading "Output" / "Output from the agent" repeated 5 times identically, which is noisy and confusing.

Compare with how `RunOutputs.tsx` handles this: it only shows the label for the first item (`label: index === 0 ? key : ""`).

You should either:
1. Group outputs under a single header per output node (preferred -- restructure to render one section per node, with multiple `OutputItem`s under it), or
2. At minimum, suppress the repeated header for subsequent results from the same node.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx [hunk 2]
```diff
@@ -37,25 +37,27 @@ export const AgentOutputs = ({ flowID }: { flowID: string | null }) => {
...
-          renderer,
-        };
+            return {
+              metadata: {
+                name: node.data.hardcodedValues?.name || "Output",
+                description:
+                  node.data.hardcodedValues?.description ||
+                  "Output from the agent",
+              },
+              value: outputData ?? "No output yet",
```
Comment (majdyz) [inline autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx]: 🤖 🔵 **Nit**: The `?? "No output yet"` fallback on this line is dead code. The `.filter()` above (`result.output_data?.output !== undefined`) already guarantees `outputData` is defined here, so the nullish coalescing operator can never trigger. This is misleading -- either remove the fallback or clarify the intent.

**Comment by majdyz** [comment]
Hey 👋 — when you've addressed the review feedback, please:

1. **Show a screenshot or recording** of the feature working end-to-end (manual test)
2. **Re-request review** from me so I get notified

Thanks for the contribution!

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx (hunk 1 above)
Comment (majiayu000) [reply autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx:61]: Already grouped in bb16de85 — one header per output node, multiple OutputItems underneath. Same approach as RunOutputs.tsx.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx (hunk 2 above)
Comment (majiayu000) [reply autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx]: Removed — the grouping refactor dropped that fallback since the filter already guards it.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx (hunk 1 above)
Comment (majiayu000) [reply autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx:61]: Already grouped in bb16de85 — one header per output node, multiple OutputItems underneath. Same approach as RunOutputs.tsx.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx (hunk 2 above)
Comment (majiayu000) [reply autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx]: Removed — the grouping refactor dropped that fallback since the filter already guards it.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx [hunk 3]
```diff
@@ -39,39 +39,49 @@ export const AgentOutputs = ({ flowID }: { flowID: string | null }) => {
...
         return {
+          nodeID: node.id,
           metadata: {
             name: node.data.hardcodedValues?.name || "Output",
             description:
               node.data.hardcodedValues?.description || "Output from the agent",
           },
-          value: outputData ?? "No output yet",
-          renderer,
+          items,
```
[the remark this answers is not in the document]
Comment (majdyz) [reply autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx:71]: 🤖 Fixed in b028719fb8: Now passing `group.metadata` to both `OutputActions` and `OutputItem` instead of empty `{}`.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx (hunk 1 above)
Comment (majdyz) [reply autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx:61]: 🤖 Confirmed — grouping looks good. Thanks for addressing this.

File: autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx (hunk 2 above)
Comment (majdyz) [reply autogpt_platform/frontend/src/app/(platform)/build/components/BuilderActions/components/AgentOutputs/AgentOutputs.tsx]: 🤖 Confirmed — dead code removed. ✓

**Comment by majiayu000** [comment]
Here is thr screenshot. @majdyz 
image
