### PR TITLE
fix(frontend/builder): Fix unnecessary graph re-saving

### LINKED ISSUE #10980: Fix unnecessary graph saving if any changes were made during the Builder session
If you open a graph in the builder, make any changes, and save it, it will still re-save if you click the save or run button even if you make no further changes. This is because the node ID isn't synced with the backend node ID on save.

### PR DESCRIPTION
**Pull request by Pwuts**
- Resolves #10980
- 2nd attempt after #11075 broke some things

Fixes unnecessary graph re-saving when no changes were made after initial save. More specifically, this PR fixes two causes of this issue:
- Frontend node IDs were being compared to backend IDs, which won't match if the graph has been modified and saved since loading.
- `fillDefaults` was being applied to all nodes (including existing ones) on element creation, and empty values were being stripped *post-save* with `removeEmptyStringsAndNulls`. This invisible auto-modification of node input data meant that in some common cases the graph would never be in sync with the backend.

### Changes 🏗️

- Fix node ID handling
  - Use `node.data.backend_id ?? node.id` instead of `node.id` in `prepareSaveableGraph`
    - Also map link source/sink IDs to their corresponding backend IDs
  - Add note about `node.data.backend_id` to `_saveAgent`
  - Use `node.data.backend_id || node.id` as display ID in `CustomNode`

- Prevent auto-modification of node input data on existing nodes
  - Prune empty values (`undefined`, `null`, `""`) from node input data *pre-save* instead of post-save
  - Related: improve typing and functionality of `fillObjectDefaultsFromSchema` (moved and renamed from `fillDefaults`)

#### For code changes:
- [x] I have clearly listed my changes in the PR description
- [x] I have made a test plan
- [x] I have tested my changes according to the test plan:
  - [x] Node display ID updates on save
  - [x] Clicking save a second time (without making more changes) doesn't cause re-save
  - [x] Updating nodes with dynamic input links (e.g. Create Dictionary Block) doesn't make the links disappear

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented unintended auto-modification of existing nodes during editing
  * Improved consistency of node and connection identifiers in saved graphs

* **Improvements**
  * Enhanced node title display logic for clearer node identification
  * Optimized data cleanup utilities for more robust input processing in the builder

### CODE REVIEW

**Comment by AutoGPT-Agent** [comment]
Thank you for addressing this graph re-saving issue! The changes look focused and appropriate for fixing the problem with node ID handling between frontend and backend.

However, I notice you have created a test plan but haven't checked off any of the test items yet. Before this PR can be merged, please:

1. Complete testing according to your test plan
2. Check off the test items in the PR description

The technical approach (using `node.data.backend_id` instead of `node.id`) looks sound, but we need verification that it works as expected and doesn't introduce any regressions.

**Comment by AutoGPT-Agent** [comment]
Thanks for this fix to prevent unnecessary graph re-saving! The changes look well-targeted and focused on the specific issue. 

I notice your test plan items haven't been checked off yet. Before this can be merged, please complete testing for all three items in your test plan to ensure this fix works as expected and doesn't have any unintended side effects:

1. Verify node display ID updates on save
2. Confirm clicking save a second time (without making more changes) doesn't cause re-save
3. Ensure updating nodes with dynamic input links doesn't make the links disappear

Once you've checked these items off, the PR should be ready for merging.

**Comment by AutoGPT-Agent** [comment]
Thank you for submitting this PR to fix the unnecessary graph re-saving issue.

Your changes look good overall. I see you've made the appropriate modifications to use `node.data.backend_id` instead of `node.id` in the relevant places. The approach makes sense to maintain the distinction between frontend and backend node IDs.

However, I noticed that you haven't completed testing according to your test plan yet:
- [ ] Node display ID updates on save
- [ ] Clicking save a second time (without making more changes) doesn't cause re-save
- [ ] Updating nodes with dynamic input links doesn't make the links disappear

Please complete the testing as outlined in your plan to ensure the changes work as expected, especially since this is a second attempt after a previous PR (#11075) had issues. Once you've verified each test case, please check them off in the PR description.

The code changes themselves look good, just need confirmation that they're working as expected.

File: autogpt_platform/frontend/src/hooks/useAgentGraph.tsx [hunk 1]
```diff
@@ -709,22 +710,26 @@ export default function useAgentGraph(
                 position,
                 data: {
                   ...frontendNode.data,
-                  hardcodedValues: removeEmptyStringsAndNulls(
-                    frontendNode.data.hardcodedValues,
-                  ),
```
Comment (Pwuts) [inline autogpt_platform/frontend/src/hooks/useAgentGraph.tsx:714]: Instead of *after* saving, I now do this *before* saving ([here](https://github.com/Significant-Gravitas/AutoGPT/pull/11145/files#diff-0ad1917a409dfebde02126122593f0fccab47c6ba44c7fb96336f69eceffbd70R599))

File: autogpt_platform/frontend/src/app/(platform)/build/components/legacy-builder/CustomNode/CustomNode.tsx [hunk 2]
```diff
@@ -158,37 +159,6 @@ export const CustomNode = React.memo(
       setIsAnyModalOpen?.(isModalOpen || isOutputModalOpen);
     }, [isModalOpen, isOutputModalOpen, data, setIsAnyModalOpen]);
 
-    const fillDefaults = useCallback((obj: any, schema: any) => {
```
Comment (Pwuts) [inline autogpt_platform/frontend/src/app/(platform)/build/components/legacy-builder/CustomNode/CustomNode.tsx:161]: Moved to [@/lib/utils](https://github.com/Significant-Gravitas/AutoGPT/pull/11145/files#diff-db26a69e6fb7546dc621634f3c8ee6efa3639e72e02837f753af18b2fdddf7beR216-R219) and improved

File: autogpt_platform/frontend/src/lib/utils.ts [hunk 3]
```diff
@@ -177,32 +181,73 @@ export function setNestedProperty(obj: any, path: string, value: any) {
...
+          if (typeof item === "object" && item !== null) {
+            fillObjectDefaultsFromSchema(item, propertySchema.items);
+          }
         }
       }
     }
   }
+
   return obj;
 }
```
Comment (Pwuts) [inline autogpt_platform/frontend/src/lib/utils.ts:252]: - Moved here from `CustomNode`
- Typed parameters
- Simplified logic
- Fixed recursive handling of arrays of objects

File: autogpt_platform/frontend/src/lib/utils.ts [hunk 4]
```diff
@@ -177,32 +181,73 @@ export function setNestedProperty(obj: any, path: string, value: any) {
...
+      if (!obj.hasOwnProperty(key)) continue;
+
+      const value = obj[key];
+      if (
+        value === null ||
+        value === undefined ||
+        (typeof value === "string" && value === "" && removeEmptyStrings)
+      ) {
+        delete obj[key];
+      } else if (typeof value === "object") {
```
Comment (Pwuts) [inline autogpt_platform/frontend/src/lib/utils.ts:208]: note to reviewers: `typeof value === "object"` includes arrays in JS

**Comment by Pwuts** [comment]
@coderabbitai review

File: autogpt_platform/frontend/src/lib/utils.ts [hunk 5]
```diff
@@ -177,32 +181,73 @@ export function setNestedProperty(obj: any, path: string, value: any) {
...
+): any {
   if (Array.isArray(obj)) {
     // If obj is an array, recursively check each element,
     // but element removal is avoided to prevent index changes.
     return obj.map((item) =>
       item === undefined || item === null
         ? ""
-        : removeEmptyStringsAndNulls(item),
+        : pruneEmptyValues(item, removeEmptyStrings),
     );
```
[the remark this answers is not in the document]
Comment (Pwuts) [reply autogpt_platform/frontend/src/lib/utils.ts:195]: this is existing logic and I'm not changing it (now)

File: autogpt_platform/frontend/src/lib/utils.ts [hunk 6]
```diff
@@ -177,32 +181,73 @@ export function setNestedProperty(obj: any, path: string, value: any) {
...
+
+export function fillObjectDefaultsFromSchema(
+  obj: Record<any, any>,
+  schema: BlockIORootSchema | BlockIOObjectSubSchema,
+) {
+  for (const key in schema.properties) {
+    if (!schema.properties.hasOwnProperty(key)) continue;
+
+    const propertySchema = schema.properties[key];
+
```
[the remark this answers is not in the document]
Comment (Pwuts) [reply autogpt_platform/frontend/src/lib/utils.ts:224]: this is existing logic and works fine (somehow)
