### PR TITLE
fix(frontend/builder): Prevent bad graph reloads

### LINKED ISSUE #10458: Builder resets changes on websocket re-connect
I was just working on a graph and after a minute or two all my changes randomly disappeared :(

[2025-07-26 12.43 vivaldi.mp4](https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/70252c93-ff27-4491-8071-635ae8c65205/f4853683-a9c7-40cb-87ef-eb82b1544da7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi83MDI1MmM5My1mZjI3LTQ0OTEtODA3MS02MzVhZThjNjUyMDUvZjQ4NTM2ODMtYTljNy00MGNiLTg3ZWYtZWI4MmIxNTQ0ZGE3IiwiaWF0IjoxNzUzNTI2NzI4LCJleHAiOjMzMzI0MDg2NzI4fQ.N8VEucCRtpxis8UJTapZIXO9RDuxI6aBNMYFSJ-MUUI)

It seems that for some reason the websocket re-connects and that causes the graph to be reloaded, discarding any changes:

### PR DESCRIPTION
**Pull request by Pwuts**
- Resolves #10458

### Changes 🏗️

Improve logic in `useAgentGraph`:
- Correctly handle unset `flowVersion` in checks in hooks
- Prevent unnecessary WebSocket re-connects
  - Remove redundant WebSocket connection management logic
- Untangle hooks for initial load and set-up
  - Simplify block filtering logic

#### For code changes:
- [x] I have clearly listed my changes in the PR description
- [x] I have made a test plan
- [x] I have tested my changes according to the test plan:
  - Edit an agent in the builder
  - [x] WebSocket doesn't re-connect unnecessarily
  - [x] Graph doesn't reset on WebSocket re-connect
  - [x] Graph doesn't reset on LaunchDarkly re-connect

### CODE REVIEW

**Comment by AutoGPT-Agent** [comment]
Thank you for your PR to fix the graph reload issues! The changes look good overall - refactoring the hooks to prevent unnecessary reloading and WebSocket reconnections should improve the builder experience.

A couple of points before we can merge:

1. **Incomplete testing**: Your checklist indicates you created a test plan but haven't completed testing against it. Please make sure to test:
   - WebSocket doesn't re-connect unnecessarily
   - Graph doesn't reset on WebSocket re-connect
   - Graph doesn't reset on LaunchDarkly re-connect

2. **Code changes**: The refactoring looks sensible, particularly:
   - Separating the WebSocket connection into its own effect
   - Converting `loadGraph` to a function instead of a callback to simplify dependencies
   - Adding a check to prevent reloading when the graph version hasn't changed
   - Moving block filtering logic to a useMemo

Once you've completed the test plan and checked those items off, this should be ready to merge. Let us know if you encounter any issues during testing!

**Comment by AutoGPT-Agent** [comment]
Thank you for your PR to fix graph reloads in the builder! The code changes look focused and appropriate for addressing the issue.

However, I noticed that your checklist isn't fully completed - the test plan still has unchecked items. Before we can merge this PR, please make sure you've tested all the items in your test plan and check them off:

- WebSocket doesn't re-connect unnecessarily
- Graph doesn't reset on WebSocket re-connect
- Graph doesn't reset on LaunchDarkly re-connect

The code changes look good, with improvements to how the graph loading and WebSocket connection are managed. I particularly like the separation of concerns between loading blocks/flows and managing the WebSocket connection, which should make the code more maintainable.

Please complete the testing and check off the remaining items in your checklist, then we can proceed with the review process.

**Comment by AutoGPT-Agent** [comment]
Thank you for this PR to fix graph reloading issues in the builder!

The changes look good from a code perspective - I can see you've improved the WebSocket connection handling and simplified the block filtering logic. The refactoring of the load graph functionality also looks more straightforward.

However, I noticed that your test plan checkboxes aren't all checked off yet. Before we can merge this PR, could you please:

1. Complete the testing according to your plan
2. Check off the remaining test items in the PR description once verified

Specifically, please confirm that:
- WebSocket doesn't re-connect unnecessarily
- Graph doesn't reset on WebSocket re-connect
- Graph doesn't reset on LaunchDarkly re-connect

Once you've completed and verified these test cases, please update the PR checklist, and we'll be ready to proceed with the review.

**Comment by AutoGPT-Agent** [comment]
Thank you for your PR addressing the graph reload issues! The changes look good, but I noticed your test plan is outlined but not marked as completed.

Before we can merge this PR, please:

1. Complete the testing according to your test plan and check off those items:
   - Verify the WebSocket doesn't re-connect unnecessarily
   - Confirm the graph doesn't reset on WebSocket re-connect
   - Ensure the graph doesn't reset on LaunchDarkly re-connect

The code changes look well-focused on the issue, particularly:
- The improved handling of unset `flowVersion`
- Removing redundant WebSocket connection logic
- Simplifying the block filtering and graph loading process

Once you've completed and checked off the test plan items, we can proceed with the review.

**Comment by AutoGPT-Agent** [comment]
Thank you for your PR fixing graph reload issues in the frontend builder! The changes look well-structured and address the referenced issue #10458.

I noticed a couple things that need attention before this can be merged:

### Test Plan Completion

In your checklist, you have one item marked as incomplete:
- [ ] WebSocket doesn't re-connect unnecessarily

Please complete all testing according to your plan and check off all items. Our process requires that all checklist items be completed before merging.

### Other Observations

Your changes look solid with good refactoring:
- Simplifying the WebSocket connection management
- Improving block filtering logic
- Preventing unnecessary graph resets

Once you've completed the testing and checked off all items in your test plan, this should be ready to go!

File: autogpt_platform/frontend/src/hooks/useAgentGraph.tsx [hunk 1]
```diff
@@ -62,38 +64,27 @@ export default function useAgentGraph(
...
-  );
+  // Filter blocks based on beta flags
+  const availableBlocks = useMemo(() => {
+    return allBlocks.filter(
+      (block) => !betaBlocks || !betaBlocks.includes(block.id),
+    );
+  }, [allBlocks, betaBlocks]);
 
-  // Load available blocks & flows
+  // Load available blocks & flows (stable - only loads once)
```
Comment (ntindle) [inline autogpt_platform/frontend/src/hooks/useAgentGraph.tsx:74]: We may want this to change tho if we flip a flag I think

File: autogpt_platform/frontend/src/hooks/useAgentGraph.tsx [hunk 2]
```diff
@@ -159,96 +150,93 @@ export default function useAgentGraph(
...
-          const prevNode = prevNodes.find((n) => n.id === node.id);
-          const flow =
-            block.uiType == BlockUIType.AGENT
-              ? availableFlows.find(
-                  (flow) => flow.id === node.input_default.graph_id,
-                )
-              : null;
-          const newNode: CustomNode = {
-            id: node.id,
+  function _loadGraph(graph: Graph) {
```
Comment (Pwuts) [inline autogpt_platform/frontend/src/hooks/useAgentGraph.tsx:153]: No changes inside this function, I just renamed it to make sure that we don't have to include it as a dependency in hooks where it's used, and so it's clear that this is not exported.

File: autogpt_platform/frontend/src/hooks/useAgentGraph.tsx [hunk 3]
```diff
@@ -159,96 +150,93 @@ export default function useAgentGraph(
...
-              sourceHandle: adjustedSourceName || undefined,
-              targetHandle: link.sink_name || undefined,
-            };
-          }),
-        );
-        return newNodes;
-      });
-    },
-    [availableBlocks, availableFlows, getOutputType],
-  );
```
Comment (Pwuts) [inline autogpt_platform/frontend/src/hooks/useAgentGraph.tsx:251]: No changes inside this function, I just renamed it to make sure that we don't have to include it as a dependency in hooks where it's used, and so it's clear that this is not exported.

File: autogpt_platform/frontend/src/hooks/useAgentGraph.tsx (hunk 1 above)
Comment (Pwuts) [reply autogpt_platform/frontend/src/hooks/useAgentGraph.tsx:74]: @0ubbe fyi if this is something you want. I'm not going to change it in this PR because we need the hotfix.
